### PR TITLE
Flag should be 5 for unpaired reads (they are still paired, just this…

### PR DESCRIPTION
**Pull request by nh13**
… end of the pair is unmapped)

### CODE REVIEW

**Comment by nh13** [comment]
My apologies for modifying the cigar.  I am not familiar enough with Pysam, and there are no unit test or integration tests that I can validate against.  I think this should do the trick.

**Comment by scottrk** [comment]
So this is a bit tough. Most of the info in the final dcs.bam file is just dummy information. We regenerate the FLAGS and CIGAR strings by realigning the final dcs reads, which then just recomputes all of these values based on this new alignment.  The old values really have little to no meaning because the underlying sequence has been modified during the consensus making (insertion of N's, etc). Why did I do it like that? Laziness, mostly. Hand computing the new CIGAR strings and what not seemed like a big pain when I could get the aligner to do it for me. All these issues could be resolved by moving to a reference free approach. That way one does not have to keep track of all this information and it's just created during a single final alignment.

**Comment by nh13** [comment]
Agreed that re-aligning the dcss' is the way to go, but the output of `DuplexMaker.py` really should be valid according to the SAM spec.  For example, try running Picard's `ValidateSamFile` tool on it, and it will fail.  If one end of the read is unmapped (in this case the sequence is all Ns) the pair flag should still be set.  

Alternatively, you could get rid of the BAM output from `DuplexMaker.py` and force user use the FASTQs directly to do the re-alignment.  That would be preferable to outputting a BAM file that does not follow the spec.

**Comment by scottrk** [comment]
That's a valid point. I'm in favor of that approach.

**Comment by nh13** [comment]
Closing in favor of https://github.com/loeblab/Duplex-Sequencing/pull/32

**Pull request closed without merging**
