### PR TITLE
Reformat README to take advantage of more Markdown syntax

### PR DESCRIPTION
**Pull request by tsibley**
This increases readability in plain text and also on the web.

### CODE REVIEW

**Comment by tsibley** [comment]
Ditto this, any chance of it being merged?

**Comment by scottrk** [comment]
I'm working on it.  There's some synchronization issues because those 
files had minor changes subsequent to your merge request.  I'm still 
fairly new to git, so I'm trying to figure out the best way to do that.

**Comment by tsibley** [comment]
@loeblab I just repushed my readme-formatting branch rebased onto your current master branch.  This includes the typo fixes recently pushed.  This PR should merge cleanly now.

**Comment by scottrk** [comment]
Thanks for reworking that for me.

**Pull request merged**
